### PR TITLE
Fix build for Debian 10

### PR DESCRIPTION
**Pull request by homdx**
- Update to QT 5.12.4
- Downgrade java JDK to 8 version
- Change to homdx repository downloader
- Decrease docker image size

### CODE REVIEW

**Comment by bbernhard** [comment]
Thanks a lot for the pull request - very much appreciated!

I saw that you replaced the benlau/qtci dependency with your own fork of the repo. I guess that's because of this pull request here (which isn't yet merged), right? https://github.com/benlau/qtci/pull/27

**Comment by homdx** [comment]
**Yes.**
Because I have a newer version in my repository.
So I had to replace the links to my fork.

If you want to merge, I will be recommit again, with restore you links and rebase it commit

**Comment by bbernhard** [comment]
Looks good to me! 

Not sure if/when @benlau will merge your changes upstream. But if he does, could you maybe do me a favor and create another pull request that changes the dependency back to the upstream repository? That would be really great.

In general I am in favor of keeping the dependencies pinned to the upstream repository. But as your pull request is not yet merged into benlau's repository, I think it's perfectly fine if we merge that pull request in the meantime. 

Thanks again for your contribution!

**Comment by homdx** [comment]
Hello. Have a nice day!

I did the adaptation work for usage : Clang with debian and update to Qt 5.13.1 version.
You need my pull request for another branch (or for master branch) after then I rebased commits?
https://github.com/homdx/qt-android-docker/tree/513

**Comment by bbernhard** [comment]
Hi,

sorry for the late reply!

Could you maybe create another pull request for your changes? (master branch is fine) That makes it easier for review :)

Thanks a lot!

**Comment by homdx** [comment]
> Hi,
> 
> sorry for the late reply!
> 
> Could you maybe create another pull request for your changes? (master branch is fine) That makes it easier for review :)
> 
> Thanks a lot!

Hello again)
I I have three options:
1. Some modified default scripts and update from 5.12 to 5.13 version of Qt
https://github.com/homdx/qt-android-docker/tree/513

2. Script with long setup: Qt 5.13.1 and recompile it from sources with Clang to armv7 architecture with openssl recompile from sources too and remove setupped Qt 5.13 and usage you recompiled version (need 20 Gb hard disk space for image and 2-4 cpu from compile 90-120 minutes for build this image)
https://github.com/homdx/qt-download-2/blob/master/Dockerfile.fullsrc

3. Script and docker image for usage this version (maked on step 2): compressed docker size 4 Gb or 2Gb for slim image
https://github.com/homdx/qt-download-2/blob/master/Dockerfile.prebuild
Or example from docker hub
https://github.com/homdx/qt-sources-android/blob/master/Dockerfile

I did not confuse you?

**Comment by bbernhard** [comment]
Cool, wasn't aware that you've created multiple versions - very nice!

I think option 1 would be perfect for this. :+1: 

Thanks for sharing the other versions too - looks really nice!

**Comment by homdx** [comment]
Hello @bbernhard 
I make Dockerfile and scripts for build Qt dev from sources for Android (branch later then Qt 6.0.0 released). Are you interested this? Make the pull request for you? You can sea it at master branch and dev in my forked repository.

**Pull request merged**
